import { assertProbesRecorded } from "./probeResults.js";

/**
 * Per-card DIRECTION control, by suspending the unwanted card ordinal at delivery.
 *
 * ── Why suspension, and not the two obvious alternatives ─────────────────────────────────────────
 *
 * A note produces one card per template, and sometimes only one of them is worth studying: に ships
 * six cards whose Recognition fronts are the bare string に, and a three-sentence self-introduction
 * is a fine Recognition card and an impossible Production one. Two mechanisms were considered and
 * struck:
 *
 *   1. Gate the template's `qfmt` on a field. An empty front is not a skipped card — it is an EMPTY
 *      card, and Anki's Tools → Empty Cards DELETES it, taking its interval and its whole review log
 *      with it.
 *   2. Omit the card row at build time. Inert on the path that actually delivers: `addNote` makes
 *      Anki generate one card per template, so a build-side omission never reaches the live
 *      collection at all. And on the .apkg side a note with a non-empty front but a missing card row
 *      is regenerated by Check Database and by any template update.
 *
 * Suspension is the only per-note direction suppression in Anki that survives routine housekeeping.
 * The consequence, stated because it is real: the .apkg keeps emitting BOTH card rows while this
 * path suspends one, so the package deliberately no longer reproduces the delivered deck
 * card-for-card.
 *
 * ── The consent model ────────────────────────────────────────────────────────────────────────────
 *
 * A card the owner has been studying for months must not silently stop appearing because of a flag
 * in a JSON file. So:
 *
 *   NEW notes (created by THIS deliver)   unconditional. A card that has never been studied has no
 *                                         scheduling to disturb. Reported exactly like `createdDecks`.
 *   ALREADY-DELIVERED notes               opt-in behind an explicit flag, with `--dry` printing every
 *                                         proposed change first — AND gated on probe evidence that
 *                                         does not exist yet, so it is currently refused outright.
 *   A HUMAN UNSUSPEND                     is permanent. A card that is unsuspended AND already
 *                                         carries this note's `dir-suspended::<ord>` tag was
 *                                         deliberately turned back on by a person; it is reported and
 *                                         never re-suspended, unless a distinct second flag says to.
 *
 * Nothing in this module contacts anything. It takes an injected client and is tested with a fake.
 */

/** The tag prefix. One tag per suspended ORDINAL, so the record survives a card being re-generated. */
export const DIR_SUSPENDED_TAG = "dir-suspended";

/** The tag for one ordinal, e.g. `dir-suspended::1`. */
export const dirSuspendedTag = (ord) => `${DIR_SUSPENDED_TAG}::${ord}`;

/**
 * The probes the DELIVERED-note path is gated on. Both are questions about a card the owner is
 * already studying, and neither has been answered:
 *
 *   `suspend-on-filtered`      a card pulled into a filtered deck has a non-zero `odid`, and nobody
 *                              has established what `suspend` does to it — whether it is suspended,
 *                              returned to its home deck first, or silently ignored.
 *   `housekeeping-unsuspends`  if a template update or Check Database clears the suspension, the
 *                              direction control quietly stops working and the owner gets the card
 *                              back with no signal.
 *
 * The NEW-note path is deliberately NOT gated on these: a note created seconds ago is in its home
 * deck, has never been studied, and has nothing for housekeeping to undo.
 */
export const DELIVERED_SUSPEND_PROBES = ["suspend-on-filtered", "housekeeping-unsuspends"];

/** The ordinals a card asks to have suspended, normalized. `[]` when the card asks for none. */
export function suspendedOrdinals(card, templateCount) {
  const raw = card?.dirSuspended;
  if (!Array.isArray(raw)) return [];
  const ordinals = [...new Set(raw)].filter(
    (ord) => Number.isInteger(ord) && ord >= 0 && ord < templateCount,
  );
  ordinals.sort((a, b) => a - b);
  return ordinals;
}

/**
 * Refuses a card that would have every direction suspended.
 *
 * Suspending both ordinals is not "hide this card" — it is a note with no studiable card at all,
 * which is what `excluded` is for and which this must never quietly produce.
 */
export function assertStudiableDirection(card, templateCount) {
  const ordinals = suspendedOrdinals(card, templateCount);
  if (ordinals.length >= templateCount) {
    throw new Error(
      `card "${card.id}" suspends every direction (${ordinals.join(", ")}), which leaves no ` +
        `studiable card. Use \`excluded\` to drop a card; \`dirSuspended\` only turns a direction off.`,
    );
  }
  return ordinals;
}

/** The card ids of one note, by template ordinal: `{ 0: 1234, 1: 1235 }`. */
async function cardOrdinals(client, noteId) {
  const cardIds = await client.findCards(`nid:${noteId}`);
  if (!cardIds?.length) return {};
  const infos = await client.cardsInfo(cardIds);
  const byOrd = {};
  for (const info of infos ?? []) {
    if (info && Number.isInteger(info.ord)) byOrd[info.ord] = info.cardId;
  }
  return byOrd;
}

/** Anki reports a suspended card as queue -1. */
const isSuspended = (info) => info?.queue === -1;

/**
 * Plans (and, when not `dry`, applies) the direction suspensions for one delivered deck.
 *
 * `notes` is `[{ card, noteId, isNew }]` — everything this deliver touched, with `isNew` true only
 * for notes IT created. Returns `{ suspended, wouldSuspend, humanUnsuspended, skippedDelivered,
 * refused }`, all lists of `{ card, noteId, cardId, ord }`, so the caller can report each class
 * separately rather than as one number.
 */
export async function applyDirectionSuspension(
  client,
  notes,
  {
    templateCount = 2,
    dry = false,
    // Opt-in for notes that already existed. Currently unreachable: the probe gate below refuses it.
    suspendDelivered = false,
    // The distinct SECOND flag. Only this re-suspends a card a person unsuspended by hand.
    reSuspendHumanUnsuspended = false,
    log = () => {},
  } = {},
) {
  const out = {
    suspended: [],
    wouldSuspend: [],
    humanUnsuspended: [],
    skippedDelivered: [],
    refused: [],
  };

  const wanted = notes
    .map((entry) => ({ ...entry, ordinals: assertStudiableDirection(entry.card, templateCount) }))
    .filter((entry) => entry.ordinals.length && entry.noteId != null);
  if (!wanted.length) return out;

  // The gate. Refused BEFORE any read, so a run that cannot legally finish never touches the
  // collection at all — and the error names the missing evidence rather than saying "disabled".
  if (suspendDelivered && wanted.some((entry) => !entry.isNew)) {
    assertProbesRecorded(
      DELIVERED_SUSPEND_PROBES,
      "suspending a direction on an ALREADY-DELIVERED note (--suspend-delivered)",
    );
  }

  for (const entry of wanted) {
    const { card, noteId, isNew, ordinals } = entry;

    // An already-delivered note is left alone unless the operator opted in. Reported, not silent:
    // the flag in cards.json says something the collection is not doing.
    if (!isNew && !suspendDelivered) {
      for (const ord of ordinals) {
        out.skippedDelivered.push({ card: card.id, noteId, cardId: null, ord });
      }
      continue;
    }

    const byOrd = await cardOrdinals(client, noteId);
    const cardIds = Object.values(byOrd);
    const infos = cardIds.length ? ((await client.cardsInfo(cardIds)) ?? []) : [];
    const infoById = new Map(infos.map((info) => [info.cardId, info]));
    const tags = await noteTags(client, noteId);

    for (const ord of ordinals) {
      const cardId = byOrd[ord];
      if (cardId == null) {
        // The card row is missing. Not something to paper over: on the AnkiConnect path Anki
        // generates one card per template, so its absence means the note or the note type is not
        // what we think it is.
        out.refused.push({
          card: card.id,
          noteId,
          cardId: null,
          ord,
          reason: "no card at ordinal",
        });
        continue;
      }
      const info = infoById.get(cardId);
      if (isSuspended(info)) continue; // already where we want it

      // THE HUMAN-OVERRIDE RULE. Unsuspended AND already tagged for this ordinal means a person
      // turned it back on after we suspended it. That is a one-click decision, and re-applying the
      // flag on every deliver would override it on a schedule.
      if (tags.includes(dirSuspendedTag(ord)) && !reSuspendHumanUnsuspended) {
        out.humanUnsuspended.push({ card: card.id, noteId, cardId, ord });
        log(
          `card ${card.id} ordinal ${ord} was unsuspended by hand after we suspended it — leaving it ` +
            `alone. Pass --re-suspend-human-unsuspended to override that decision.`,
        );
        continue;
      }

      if (dry) {
        out.wouldSuspend.push({ card: card.id, noteId, cardId, ord, from: "unsuspended" });
        continue;
      }
      await client.suspend([cardId]);
      await client.addTags([noteId], dirSuspendedTag(ord));
      out.suspended.push({ card: card.id, noteId, cardId, ord });
    }
  }

  return out;
}

async function noteTags(client, noteId) {
  const [info] = (await client.notesInfo([noteId])) ?? [];
  return info?.tags ?? [];
}

/** The `--dry` line for one proposed change: note, card, ordinal, from-state, to-state. */
export function describeSuspension(entry, templateNames = ["Recognition", "Production"]) {
  const name = templateNames[entry.ord] ?? `ord ${entry.ord}`;
  return (
    `  ${entry.card}  note ${entry.noteId}  card ${entry.cardId ?? "?"}  ` +
    `ord ${entry.ord} (${name})  ${entry.from ?? "unsuspended"} -> suspended`
  );
}
