// The ElevenLabs text-to-speech model used for every clip. `eleven_v3` produces noticeably more
// natural Japanese (and other languages) than the older `eleven_multilingual_v2`, at the same cost
// (1 credit / character). Overridable per run via ANKI_BUILDER_TTS_MODEL.
//
// The audio cache is segmented by this value (audio/<voiceId>/<model>/…) so switching models never
// serves a stale clip generated by a different model — the same text under two models hashes to the
// same filename, but lives in a different model directory.
export const TTS_MODEL = process.env.ANKI_BUILDER_TTS_MODEL || "eleven_v3";
